-- Leading or trailing commas.
-- Order by default order is ascending
-- Foreign key: A column in a table that maps  to o refers to a primary key in another table.
-- Shorting cast -> coupon::int as coupon_cast_int